### ISSUE TITLE
Bug: GH Action runner's built-in `terraform` binary over-rides the one installed by `tenv`

### ISSUE THREAD

**Issue by RDhar** [tofuutils/tenv#98]
### Description

Following on from #93, it'd appear that VMs with built-in `terraform` binary—such as [GH Action runner](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#:~:text=SVN%201.14.1-,Terraform%201.7.5,-yamllint%201.35.1)—overrides the `tenv ... use` selection.

### Replication

1. View the workflow logs after running the following GH Action step.
    ```yml
    jobs:
      tf:
        runs-on: ubuntu-latest
        steps:
          - run: |
              LATEST_TENV=$(curl --silent https://api.github.com/repos/tofuutils/tenv/releases/latest | jq -r .tag_name)
              curl -O -L "https://github.com/tofuutils/tenv/releases/latest/download/tenv_${LATEST_TENV}_amd64.deb"
              sudo dpkg -i "tenv_${LATEST_TENV}_amd64.deb"
              tenv terraform use 1.6.1
              terraform --version
    ```
1. Alternatively, a working demo of this workflow is [available here](https://github.com/DevSecTop/TF-via-PR-Comments/pull/193/files).

### Expected behavior

The output of `terraform --version` should match that of used/installed by `tenv`.

```sh
$ tenv terraform use 1.6.1
$ terraform --version
...
Installation of Terraform 1.6.1 successful
Written 1.6.1 in /home/runner/.tenv/Terraform/version
Terraform v1.6.1
on linux_amd64
```

### Actual behavior

The output of `terraform --version` reflects the built-in/pre-installed version of `terraform`, ignoring `tenv` altogether.

```sh
Installation of Terraform 1.6.1 successful
Written 1.6.1 in /home/runner/.tenv/Terraform/version
Terraform v1.7.5
on linux_amd64
```

### Screenshots

[Link to existing workflow log](https://github.com/DevSecTop/TF-via-PR-Comments/actions/runs/8572655810/job/23495699988#step:3:49) which demonstrates the output of the above replication steps.

### Environment (please complete the following information):

Sourced from [actions/runner-images](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md):
- OS Version: 22.04.4 LTS
- Kernel Version: 6.5.0-1016-azure
- Image Version: 20240324.2.0
- Systemd version: 249.11-0ubuntu3.12

### Additional context

Cannot emphasise how appreciative I am of your efforts towards lowering the barrier-to-entry for O/TF, especially in CI contexts such as this. Thank you for your time!
